# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='login.proto',
  package='network',
  serialized_pb=_b('\n\x0blogin.proto\x12\x07network\"-\n\x08\x63s_login\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x02(\t\x12\x10\n\x08password\x18\x02 \x02(\t\"*\n\x08sc_login\x12\x0e\n\x06result\x18\x01 \x02(\r\x12\x0e\n\x06reason\x18\x02 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CS_LOGIN = _descriptor.Descriptor(
  name='cs_login',
  full_name='network.cs_login',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='network.cs_login.account', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password', full_name='network.cs_login.password', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=69,
)


_SC_LOGIN = _descriptor.Descriptor(
  name='sc_login',
  full_name='network.sc_login',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='network.sc_login.result', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reason', full_name='network.sc_login.reason', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=113,
)

DESCRIPTOR.message_types_by_name['cs_login'] = _CS_LOGIN
DESCRIPTOR.message_types_by_name['sc_login'] = _SC_LOGIN

cs_login = _reflection.GeneratedProtocolMessageType('cs_login', (_message.Message,), dict(
  DESCRIPTOR = _CS_LOGIN,
  __module__ = 'login_pb2'
  # @@protoc_insertion_point(class_scope:network.cs_login)
  ))
_sym_db.RegisterMessage(cs_login)

sc_login = _reflection.GeneratedProtocolMessageType('sc_login', (_message.Message,), dict(
  DESCRIPTOR = _SC_LOGIN,
  __module__ = 'login_pb2'
  # @@protoc_insertion_point(class_scope:network.sc_login)
  ))
_sym_db.RegisterMessage(sc_login)


# @@protoc_insertion_point(module_scope)
